version: "3"

services:
  web:
    image: "php:8.0.7-apache"
    restart: 'always'
    ports:
      - '80:80'
    volumes:
      - ./www:/var/www/html/
      - C:/Users/jsomh/Documents/GarminExport:/var/www/html/garmin